In [1]:
import numpy as np
import pandas as pd
import torch
# num = []
# i=0
# while i<6:
#     num.append((np.random.randint(1,101,size=3)*.01).tolist())
#     i+=1
# inputs = torch.tensor(num)
inputs = torch.tensor([
    [.43,.15,.89],
    [.55,.87,.66],
    [.57,.85,.64],
    [.22,.58,.33],
    [.77,.25,.10],
    [.05,.80,.55]
])


A the second input element
B the input embedding size, d=3
C the output embedding size, d_out=2

We need to initialize the size that matches with the input column dimension for matrix calculation

In [ ]:
x_2 = inputs[1] #A 1 means taking "Journey" as query for 
d_in = inputs.shape[1]  #B 1 means column size which is 3, 6X3
d_out = 2 #C for illustration we are using 2 otherwise it will be same as d_in

Initialize 3 weigt matrix Wq, Wk and Wv

In [5]:
torch.manual_seed(45)
W_query = torch.nn.Parameter(torch.rand(d_in,d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
print(W_query,"\n\n Key:", W_key, "\n\n Value:", W_value)

Parameter containing:
tensor([[0.1869, 0.9613],
        [0.6834, 0.8988],
        [0.0505, 0.5555]]) 

 Key: Parameter containing:
tensor([[0.7861, 0.0566],
        [0.7842, 0.1480],
        [0.0388, 0.1037]]) 

 Value: Parameter containing:
tensor([[0.4216, 0.2373],
        [0.8111, 0.5340],
        [0.6834, 0.6528]])


Journey vector is multiplied with query, key and value

In [12]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value

print(query_2)


tensor([0.7308, 1.6773])


inputs and each q,k,v matrix multiplied

In [14]:
query = inputs @ W_query
key = inputs @ W_key
value = inputs @ W_value
print(query)

tensor([[0.2279, 1.0425],
        [0.7308, 1.6773],
        [0.7198, 1.6674],
        [0.4542, 0.9161],
        [0.3199, 1.0205],
        [0.5839, 1.0726]])


In [ ]:
atten_scores_2 = query_2 @ key.T
print(atten_scores_2) # for getting attn score of Journey and key matrix

tensor([0.5912, 1.2163, 1.2092, 0.6904, 0.7410, 0.8018])


In [18]:
attn_scores = query @ key.T 
print(attn_scores) # for getting all the query with all other keys

tensor([[0.2565, 0.4979, 0.4936, 0.2841, 0.2783, 0.3426],
        [0.5912, 1.2163, 1.2092, 0.6904, 0.7410, 0.8018],
        [0.5844, 1.2015, 1.1945, 0.6821, 0.7313, 0.7925],
        [0.3499, 0.7271, 0.7232, 0.4124, 0.4491, 0.4758],
        [0.2985, 0.5978, 0.5935, 0.3401, 0.3504, 0.4020],
        [0.4352, 0.9107, 0.9061, 0.5162, 0.5677, 0.5929]])


scale by sqrt(d-keys) - for stability in learning

In [23]:
d_k = key.shape[-1] ##-1 means selecting the column
attn_weights_2 = torch.softmax(atten_scores_2/np.sqrt(d_k),dim=-1)
print(attn_weights_2)
print(d_k)

tensor([0.1342, 0.2089, 0.2078, 0.1440, 0.1493, 0.1558])
2
